### PR TITLE
fix(selftest): fail task when test failed

### PR DESCRIPTION
**Pull request by MartinBasti**
Block CI by failing when test fails.

### CODE REVIEW

**Review by Josh-Everett — APPROVED** [review]

**Review by dirgim — APPROVED** [review]
LGTM

**Comment by MartinBasti** [comment]
fixed another uncaught error

**Review by hongweiliu17 — APPROVED** [review]
LGTM

**Review by dirgim — APPROVED** [review]
LGTM

**Comment by MartinBasti** [comment]
And it failed again on another error :sob:

**Comment by dirgim** [comment]
> ```
> not ok 10 /project/image/fbc-labels-fail
> # (in test file /project/conftest.sh, line 59)
> #   `[ "$status" -eq 1 ]' failed
> ```
> 
> I checked image and it has all required labels, so this test either never worked or the image changed `skopeo inspect --no-tags docker://quay.io/redhat-appstudio/sample-image:test-index-fail-2 > fbc_label_fail.json`
> 
> @dirgim

Yes, I set the wrong policy file in that test - it should be `$POLICY_PATH/image/fbc-labels.rego` (https://github.com/redhat-appstudio/hacbs-test/blob/main/policies/image/fbc-labels.rego)

**Comment by MartinBasti** [comment]
fixed: I forgot to commit and push fix, sorry for delay :D

**Review by dirgim — APPROVED** [review]
LGTM

**Pull request merged**
