### PR TITLE
Add ppc64le support

### PR DESCRIPTION
**Pull request by snehakpersistent**
This PR is to add ppc64le support to hacbs-test and clamav-db images.

### CODE REVIEW

**Comment by snehakpersistent** [comment]
@jsztuka @srivickynesh can you please assign this for review?

**Review by jsztuka — APPROVED** [review]
lgtm

**Comment by jsztuka** [comment]
Could you please provide/create story about this change??

**Comment by snehakpersistent** [comment]
@jsztuka I have created story https://issues.redhat.com/projects/HACBS/issues/HACBS-921.
@srivickynesh @dirgim can you please review this?

**Review by dirgim — APPROVED** [review]
LGTM

**Review by srivickynesh — APPROVED** [review]
LGTM

**Pull request merged**
