### PR TITLE
Add gosec to hacbs-test Docker image

### PR DESCRIPTION
**Pull request by staticf0x**
This adds prerequisites for HACBS-223 (go, gosec and git (for git cloning the source repo)).

### CODE REVIEW

**Comment by staticf0x** [comment]
Actually `git` might not be needed, when we already have the `git-clone` task

**Comment by dirgim** [comment]
> Actually `git` might not be needed, when we already have the `git-clone` task

Yeah, I was just wondering about that. I think we should be good without it to keep the container size down.

**Comment by staticf0x** [comment]
I removed the `git` dependency, since we have `git-clone` task. Can you review it now please?

**Comment by staticf0x** [comment]
Changed the target branch to `feature-sast`

**Review by dirgim — APPROVED** [review]
LGTM

**Review by srivickynesh — APPROVED** [review]
LGTM

**Pull request merged**
