### PR TITLE
feat(1509): Adding yq to worker image

### PR DESCRIPTION
**Pull request by jsztuka**
Signed-off-by: Jiri Sztuka <jsztuka@redhat.com>
This change is needed as prerequisite for upcoming PR creation in build-definitions.

### CODE REVIEW

**Review by srivickynesh — APPROVED** [review]
LGTM

**Comment by MartinBasti** [comment]
Are you willing to add quicktest into `selftest.sh` to make sure the installed `yq` CLI works and is present?

**Review by hongweiliu17 — APPROVED** [review]
LGTM

**Comment by jsztuka** [comment]
> Are you willing to add quicktest into `selftest.sh` to make sure the installed `yq` CLI works and is present?

Added simple test for making yq is present.

**Pull request merged**
